# Generated by Django 5.1.1 on 2024-10-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='autor',
            new_name='usuario',
        ),
    ]
